# This is the configuration used to check the rubocop source code.
AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - lib/**/*
  Exclude:
    - templates/**/*
inherit_from: rubocop-todo.yml
